
export const GET_ARTIST_REQUESTED='GET_ARTIST_REQUESTED';
export const GET_ARTIST_SUCCESS='GET_ARTIST_SUCCESS'; 
export const GET_ARTIST_FAILED='GET_ARTIST_FAILED';
//********************************************** */
export const GET_SINGLE_SONG_SUCCESS='GET_SINGLE_SONG_SUCCESS';
export const GET_SINGLE_SONG_FAILED='GET_SINGLE_SONG_FAILED';
export const GET_SINGLE_SONG_REQUESTED='GET_SINGLE_SONG_REQUESTED';
